environment:
  matrix
  - nodejs_version : "14"

  install
    - ps: Install-Product node $env:nodejs_verison
    - npm install

    test_script:

    -node --version
    -npm --version

    -npm test

build: off